Added Management URL for Mac Configuration Command
netbirdio/dashboard pull request #83
Opened 2022-09-24 16:33 UTC by ashutoshpw

2022-09-24 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/dashboard?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/dashboard?pullRequest=83) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/dashboard?pullRequest=83) it.</sub>

2022-09-26 08:36 UTC, braginini commented
Hey @ashutoshpw 
Thank you for contributing! Great job!

2022-09-26 08:48 UTC, braginini commented
@ashutoshpw 
Could you please split things into separate PRs? 
E.g. gitpod in unrelated to the AddPeer views.

2022-09-26 08:51 UTC, braginini requested changes

2022-09-26 08:51 UTC, braginini commented on .gitpod.yml
> +## in Auth0 -> Application -> Settings
I think that gitpod integration should come as a separate PR

2022-09-26 08:51 UTC, braginini commented on example.env
> +AUTH_CLIENT_ID=*****************************
Same as with gitpod.
I think that the dev flow improvement should come separately from the UI Changes

2022-09-26 10:35 UTC, ashutoshpw commented
Sure, will do that.

2022-11-10 20:07 UTC, mlsmaycon commented
Hello @ashutoshpw, in the next couple of weeks we will be pushing some changes to the add-peer page. 

Let us know how you feel about the requested changes, we would love to get your contribution

2022-12-07 20:02 UTC, closed without merging